# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://Xuhbxbushoijspinosjbijsnx.github.io"
baseurl: "/moonrise"
siteIcon: /media/9188D814-D6B6-40DA-94E2-14D256D7499A.png
siteYear: 2020
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: NoClue RP
serverDescription: Minecraft Server Based on CityRP.
serverIP: 138.201.133.35:25567
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/JYtT28ck7g
discordServerID: 838698819545071627
discordChannelID: 838698820673863690


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
